SELECT
    UNIDAD_DE_NEGOCIO,
    ZONA_REGION,
    DESC_REGIAO,
    CUSTOMER_ID,
    LLAVE,
    MIN(FECHA) AS MIN_FECHA,
    MAX(FECHA) AS MAX_FECHA,
    SUM(TRANSACTIONS) AS TRANSACTIONS_OF_DAY,
    SUM(TOTAL_TRANSACTION) AS MONEY_OF_DAY,
    COUNT(DISTINCT FECHA) AS COUNT_FECHAS,
    SUM(PRODUCTOS_POR_TRANSACCION / TRANSACTIONS) AS APROX_VOLUME,
    SUM(PRODUCTOS_POR_TRANSACCION) AS PRODUCTS_OF_DAY
FROM (
    SELECT
        B.ID_DIA AS FECHA,
        C.UNIDAD_DE_NEGOCIO,
        ZONA_REGION,
        DESC_REGIAO,
        TRIM(TO_CHAR(A.ID_CLIENTE)) AS CUSTOMER_ID,
        C.UNIDAD_DE_NEGOCIO || C.ZONA_REGION || C.DESC_REGIAO || TRIM(TO_CHAR(A.ID_CLIENTE)) AS LLAVE,
        C.COD_LOJA AS TIENDA,
        SUM(B.VALOR_PV) AS TOTAL_TRANSACTION,
        COUNT(DISTINCT B.ID_DIA||B.ID_POS||B.ID_OPERADOR||B.ID_LOJA||B.N_TRANSACCAO) AS TRANSACTIONS,
        SUM(CASE WHEN MOD(B.QTE, 1) <> 0 THEN 1 ELSE (B.QTE) END ) AS PRODUCTOS_POR_TRANSACCION
    FROM DWH_CO_V.gen_lkp_loja_v C
    INNER JOIN DWH_CO_V.VEN_B_VENDA_V B ON C.COD_LOJA=B.ID_LOJA
    LEFT JOIN DWH_CO_V.VEN_B_CTLOG_V A ON B.ID_DIA = A.ID_DIA
    AND  B.ID_LOJA = A.ID_LOJA
    AND  B.ID_POS = A.ID_POS
    AND  B.ID_OPERADOR = A.ID_OPERADOR
    AND  B.N_TRANSACCAO = A.TR_NUMBER
    INNER JOIN (
        SELECT C.CUSTOMER_ID
        FROM COL_MKT.INFO_PER_CUSTOMER C
        LEFT JOIN
        COL_MKT.CUSTOMER_PREDICTIONS P
        ON C.UNIDAD_DE_NEGOCIO = P.UNIDAD_DE_NEGOCIO
        AND C.ZONA = P.ZONA
        AND C.REGION = P.REGION
        AND C.CUSTOMER_ID = P.CUSTOMER_ID
        WHERE P.CUSTOMER_ID IS NULL
        QUALIFY ROW_NUMBER() OVER (ORDER BY C.CUSTOMER_ID) BETWEEN {start} AND {end}
    ) CU ON CU.CUSTOMER_ID = TRIM(TO_CHAR(A.ID_CLIENTE))
    WHERE B.ID_DIA BETWEEN CAST('20240228' AS DATE FORMAT 'yyyymmdd') AND CAST('20240531' AS DATE FORMAT 'yyyymmdd')
    GROUP BY
        1, 2, 3, 4, 5, 6, 7
) AS A
GROUP BY
    1, 2, 3, 4, 5;